### ISSUE TITLE
Add a compiled, minified release of js and css

### ISSUE THREAD

**Issue by pcambra** [Irubataru/tiny-html-audio-player#13]
This would allow to include the library through jsdeliver or other github cdns

Happy to help :)

Related to: https://github.com/Irubataru/tiny-html-audio-player/issues/7

**Comment by Irubataru** [comment]
Hiya. I don't know all that much about web development and packages for JS, but I am very interested in learning. Do you simply want minified versions of the js and css added to a release, or is there something else? I can easily do that.

**Comment by pcambra** [comment]
That'd be fantastic yes, also it would be great to remove the jquery dependency? I've added https://www.drupal.org/project/tiny_html_audio_player as a Drupal project based in this :) and jquery will be gone from Drupal next year

**Comment by Irubataru** [comment]
I'll add minified versions later today, that's simple enough. As for removing jquery, that is quite a big undertaking as it is used all throughout. You're welcome to open a PR for it if you'd like.

**Comment by pcambra** [comment]
Many thanks @Irubataru, great to hear that you're open for it

**Comment by Irubataru** [comment]
I've created a new release and added minified versions to that. Hope that's what you needed.

As for removing jquery I am all for improving things. I understand that jquery is quite outdated and that there are better ways of doing things now. so it would probably be good to get rid of it.
