### ISSUE TITLE
preload="none" not respected

### ISSUE THREAD

**Issue by paulOr** [Irubataru/tiny-html-audio-player#8]
When adding preload="none" attribute to <audio> tag, its not respected

**Comment by Irubataru** [comment]
It seems like the `Howl` constructor takes a preload option, so if all there is to it is to add that then it should be fairly straight forward. I'll have a look at it when I have time a make a PR you can test, unless you want to make it yourself.

**Comment by Irubataru** [comment]
I created a pull request for a small fix (#9), could you check if it satisfies your requirements?
